### ISSUE TITLE
Display a warning text when there is no data to graph in Data

### ISSUE THREAD

**Issue by ethankale** [ethankale/Sedna#80]
Right now the graph in Data just remains on the last graph if there is no data to display.  It should wipe the graph and display an error.

**Comment by Gautam-Arora24** [comment]
May I work on this issue?

**Comment by ethankale** [comment]
@Gautam-Arora24 I wouldn't mind some help, but this is a pretty specialized program - could be challenging to get up to speed.  If you want to mess around & submit a PR, that would be OK.
